#!/bin/bash
echo "          %%%%%%%%%%%%%           %%%%%%%%%%%          "
echo "      %%%%%           %%%%    %%%%          %%%%%      "
echo "     %%%%%               %%%%%%%              %%%%%    "
echo "    %%% %%%%%%%%%          %%%             %%%%% %%%   "
echo "    %%     %%%%%%           %           %%%%%     %%%  "
echo "    %%        %%%%%%%               %%%%%%         %%  "
echo "    %%           %%%%%%%        %%%%%%%%          %%%  "
echo "     %%             %%%%%%%   %%%%%%             %%%   "
echo "      %%                %%%%%%%%%               %%     "
echo "       %%%             %%%%%%%%%%             %%%      "
echo "         %%%        %%%%%%    %%%%%%        %%%        "
echo "           %%%   %%%%%%         %%%%%%%   %%%          "
echo "             %%%%%%%                 %%%%%%            "
echo " Heartless      %%%                  %%%               "
echo " Automated        %%%              %%%                 "
echo " Correction         %%%          %%%                   "
echo " Script V1.0          %%        %%                     "
echo "                       %%      %%                      "
echo " Made by:              %%      %%                      "
echo " Fabio Facilla         %%       %%                     "
echo "                   %%%%%         %%%%%                 "
echo "             %%%%%%%                %%%%%%%%           "
echo "                %%%%%%%%%      %%%%%%%%%%              "
echo "                       %%%    %%%                      "
echo " Please report any bug  %%%  %%%                       "
echo " you find on Slack        %%%%%                        "
echo "                            %                          "
echo " HACS will now try to update itself..."
read -p 'Press any key to continue or CTRL + C to stop
' -n1 -s
git pull https://github.com/White-Heartless/HACS